# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2019.6.16-hecc5488_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-8.2.0-hdf63c60_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-3.0.0-1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-8.2.0-hdf63c60_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandoc-2.7.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.6-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/c-ares-1.15.0-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.5-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.2-hf484d3e_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9c-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.15-h516909a_1005.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.16-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.8.3-he1b5a44_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openblas-0.3.5-ha44fe06_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1b-h14c3975_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pcre-8.43-he6710b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.9-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.1.7-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h14c3975_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/boost-cpp-1.68.0-h11c811c_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-hc5be6a0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-7_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20170329-hf8c457e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.37-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libprotobuf-3.6.1-hdbcaa40_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.9-h13577e0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-7.0-hf8c457e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.9-hed695b0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.3.1-hf484d3e_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zstd-1.4.0-h3b9ef0a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.10.0-he983fc9_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.56.2-had28632_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.16.3-h05b26f9_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-7_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.8.0-7_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.0.10-h57b8799_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.28.0-h8b20d00_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/thrift-cpp-0.12.0-h0a07b25_1002.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.2-h714fa37_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-he4413a7_1000.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gstreamer-1.14.0-hb453b48_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-2.7.15-h721da81_1008.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/asn1crypto-0.24.0-py27_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports_abc-0.5-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2019.6.16-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py27_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/crcmod-1.7-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cython-0.29.10-py27he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.5.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dill-0.2.9-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/docopt-0.6.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/enum34-1.1.6-py27_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fastavro-0.21.23-py27h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/funcsigs-1.0.2-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/functools32-3.2.3.2-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/futures-3.2.0-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-resumable-media-0.3.2-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gst-plugins-base-1.14.0-hbbd80ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/httplib2-0.11.3-py27_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/idna-2.8-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipaddress-1.0.22-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kiwisolver-1.1.0-py27hc9558a2_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.1.1-py27h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mistune-0.8.4-py27h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mmh3-2.5.1-py27hf484d3e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.16.4-py27h95a1406_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ptyprocess-0.6.0-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pycparser-2.19-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyhamcrest-1.9.0-py_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pykerberos-1.1.14-py27h2de3caf_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyrsistent-0.15.2-py27h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-avro-1.8.2-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2019.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyvcf-0.6.8-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-3.13-py27h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyzmq-18.0.1-py27hc4ba49a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scandir-1.10.0-py27h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/simplegeneric-0.8.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/singledispatch-3.4.0.3-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sip-4.18.1-py27hf484d3e_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/subprocess32-3.5.4-py27h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/testpath-0.4.2-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/typing-3.6.6-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/arrow-cpp-0.12.1-py27h0e61e49_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.shutil_get_terminal_size-1.0.0-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.12.3-py27h8022711_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/configparser-3.7.3-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-19.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pathlib2-2.3.3-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pexpect-4.7.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-6.0.0-py27he7afcd5_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pydot-1.2.4-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/qt-5.6.3-h8bf5577_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rsa-3.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-41.0.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-5.1.1-py27h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traitlets-4.3.2-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.5-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-2.7-py27h72c5cf5_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/entrypoints-0.3-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-1.6.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/grpcio-1.16.1-py27hf8bcb03_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.10.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jsonschema-3.0.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_core-4.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nose-1.3.7-py27_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/oauth2client-2.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parquet-cpp-1.5.1-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pickleshare-0.7.5-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/protobuf-3.6.1-py27hf484d3e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.4.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyqt-5.6.0-py27h13b7fb3_1008.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/terminado-0.8.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wheel-0.33.4-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bokeh-1.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/googleapis-common-protos-1.6.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_client-5.2.4-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-base-2.2.3-py27h60b886d_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-4.4.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-19.1.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-1.0.15-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyarrow-0.12.1-py27hbbcf98d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-19.0.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/googleapis-common-protos-grpc-1.6.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipython-5.8.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-2.2.3-py27h8a2030e_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbconvert-5.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pbr-5.2.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/urllib3-1.24.3-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/grpc-google-iam-v1-0.11.4-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipykernel-4.10.0-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mock-2.0.0-py27_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-2.22.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/google-api-core-1.11.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/notebook-5.7.8-py27_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/requests-kerberos-0.12.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/google-api-core-grpc-1.11.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nb_conda_kernels-2.2.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-hdfs-2.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/widgetsnbextension-3.4.2-py27_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipywidgets-7.4.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nb_conda-2.2.1-py27_2.tar.bz2
