#!/bin/bash

set -ev

# Update jupyterlab version and install labextensions
conda install -yq 'jupyterlab>=1.0' jupyterlab_code_formatter black
jupyter labextension install @jupyter-widgets/jupyterlab-manager 
jupyter labextension install @jupyterlab/toc
jupyter labextension install jupyterlab_bokeh
jupyter labextension install @ryantam626/jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter

mkdir -p opt

pushd opt
wget --quiet http://apache.forsale.plus/flink/flink-1.9.1/flink-1.9.1-bin-scala_2.11.tgz && tar -xf flink-1.9.1-bin-scala_2.11.tgz
wget --quiet http://apache.forsale.plus/kafka/2.3.1/kafka_2.11-2.3.1.tgz && tar -xf kafka_2.11-2.3.1.tgz
wget --quiet https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && rm ngrok-stable-linux-amd64.zip
popd
