#!/bin/bash

conda info --envs

conda activate -n beam-notebook-demo
conda install --file spec-file.txt
pip install "git+https://github.com/ostrokach/beam.git@feature/filebasedcache#egg=apache_beam[gcp]&subdirectory=sdks/python"
