#!/bin/bash

pushd opt
./kafka_2.11-2.3.1/bin/zookeeper-server-start.sh ./kafka_2.11-2.3.1/config/zookeeper.properties > zookeeper.log &
(sleep 10 && ./kafka_2.11-2.3.1/bin/kafka-server-start.sh ./kafka_2.11-2.3.1/config/server.properties > kafka.log) &
popd

exec "$@"
