#!/bin/bash

# mkdir -p ~/logs

# pushd opt
# ./flink-1.9.1/bin/start-cluster.sh
# ./kafka_2.11-2.3.1/bin/zookeeper-server-start.sh ./kafka_2.11-2.3.1/config/zookeeper.properties > ~/logs/zookeeper.log &
# (sleep 10 && ./kafka_2.11-2.3.1/bin/kafka-server-start.sh ./kafka_2.11-2.3.1/config/server.properties > ~/logs/kafka.log) &
# ./ngrok http 8081 -log=stdout > ~/logs/ngrok.log
# popd

exec "$@"
